### ISSUE TITLE
Evaluator.Parse() throws unexpected exceptions

### ISSUE THREAD

**Issue by mschessler** [KovtunV/NoStringEvaluating#14]
Evaluator.Parse() throws unexpected exceptions on malformed input.

Example 1:
```
var facade = NoStringEvaluator.CreateFacade();
var evaluator = facade.Evaluator;
evaluator.Calc("0(!(");
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at NoStringEvaluating.Functions.Logic.NotAliasFunction.Execute(List`1 args, ValueFactory factory)
   at NoStringEvaluating.NoStringEvaluator.CalcFunction(FunctionWrapperNode functionWrapper, VariablesSource variables, ValueKeeperContainer valueKeeperContainer)
   at NoStringEvaluating.NoStringEvaluator.CalcInternal(List`1 nodes, VariablesSource variables, ValueKeeperContainer valueKeeperContainer)
   at NoStringEvaluating.NoStringEvaluator.OnCalcAggregated(List`1 nodes, VariablesSource variables)
   at NoStringEvaluating.NoStringEvaluator.Calc(String formula)

Example 2:
`evaluator.Calc("(");`

System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Pop()
   at NoStringEvaluating.NoStringEvaluator.CalcInternal(List`1 nodes, VariablesSource variables, ValueKeeperContainer valueKeeperContainer)
   at NoStringEvaluating.NoStringEvaluator.OnCalcAggregated(List`1 nodes, VariablesSource variables)
   at NoStringEvaluating.NoStringEvaluator.Calc(String formula)

**Comment by KovtunV** [comment]
This is expected behavior. I did it to not to decrease performance because of function checking. Alternatively I created another service to validate formula input.

Example 1:
![image](https://github.com/KovtunV/NoStringEvaluating/assets/11136226/fd1d2e3b-9af6-4ea4-ac85-74936f4e9c1c)

Example 2:
![image](https://github.com/KovtunV/NoStringEvaluating/assets/11136226/b98b2533-9087-4a0e-b3d8-b2b03582172c)

**Comment by SyrasX** [comment]
Hey, thanks for the fast answer. I was not aware of the check syntax function. The problem unfortunately still remains.
New inputs that pass the check function but still crash:

";;"
-> System.InvalidOperationException

"-(!())"
-> System.ArgumentOutOfRangeException

**Comment by KovtunV** [comment]
If you share the results, I will be grateful)

On the other hand, I'm not sure should I validate functions or not. For example, "UPPER()" will throw as well, I left it to show an error immediately. I mean if exception throws user can review formula immediately, but if I will return some value, even my wrapper around null, user can realize that later, even on production
